# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6af14af0ab1694c9a2b882304c41b9e1ee5e104c378e7932737b497b6a56ac9229eda7a292950db05e1d115482ad7c9a47719cf02d9b3eeec34318e5d69e2a4e

test:
  secret_key_base: fabebd736993ebbe3d2ee331f3914c03b259bc2e2d15cfe6bf9a9d6cdfe3a9f5f21040de5c1fe366af040d62042e32d1a2afb9f55f7a78a2483a820b87abbc85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
